### PR TITLE
Net 1173 b: improvements to network setup wizard

### PR DESCRIPTION
**Pull request by pwilson77**

### CODE REVIEW

**Review by Aceix — CHANGES_REQUESTED** [review]
@pwilson77 fix merge conflicts. also, has it been signed off by QA/@afeiszli ?

**Comment by pwilson77** [comment]
> @pwilson77 fix merge conflicts. also, has it been signed off by QA/@afeiszli ?

Fixed merged conflicts... QA is testing  now

**Review by Aceix — CHANGES_REQUESTED** [review]
revert changes in `index.html` and `vite.config.ts`

**Comment by pwilson77** [comment]
> revert changes in `index.html` and `vite.config.ts`

**Review by Aceix — APPROVED** [review]

**Pull request merged**
